import "./globals.css";
import { Inter } from "next/font/google";
import { Vazirmatn } from "next/font/google";
const vazirmatn = Vazirmatn({
  subsets: ["arabic", "latin"],
  variable: "--font-vazirmatn",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth" lang="en">
       <meta name="theme-color" content="#F9FAFB" />
      <meta
        name="apple-mobile-web-app-status-bar-style"
        content="#F9FAFB"
      ></meta>
      <body
        className={`${vazirmatn.variable} ${inter.variable}  min-h-screen bg-gray-50`}
      >
        {children}
      </body>
    </html>
  );
}
