import "./globals.css";
import { Vazirmatn } from "next/font/google";
const vazirmatn = Vazirmatn({
  subsets: ["arabic", "latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth" lang="en"  dir="rtl">
       <meta name="theme-color" content="#F9FAFB" />
      <meta
        name="apple-mobile-web-app-status-bar-style"
        content="#F9FAFB"
      ></meta>
      <body
        className={`${vazirmatn.className} min-h-screen bg-gray-50`}
      >
        {children}
      </body>
    </html>
  );
}
